import { useState } from 'react';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { Button, Card, Field } from '../shared';

const initial = { apellidoPaterno:'', apellidoMaterno:'', nombres:'', fechaNacimiento:'', lugarNacimiento:'', genero:'', calle:'', numeroCasa:'', colonia:'', municipio:'', estado:'', pais:'México', telefono:'', telefonoCelular:'', correo:'', beneficiarioNombres:'', beneficiarioRelacion:'', beneficiarioDomicilio:'', beneficiarioTelefono:'', patrocinadorNombres:'', numeroPatrocinador:'', lugarFirma:'', fechaFirma:'' };
export default function FormularioMembresia({ onClose }) {
  const [form, setForm] = useState(initial);
  const change = (e) => setForm((s)=>({ ...s, [e.target.name]: e.target.value }));
  const dividirFecha = (fechaISO) => { if (!fechaISO) return { dd:'', mm:'', aaaa:'' }; const [aaaa, mm, dd] = fechaISO.split('-'); return { dd, mm, aaaa }; };
  const generarPDF = async () => { try { const bytes = await fetch('/archivos/SOLICITUD-DE-MEMBRESIA-v2.pdf').then((r)=>r.arrayBuffer()); const pdfDoc = await PDFDocument.load(bytes); const font = await pdfDoc.embedFont(StandardFonts.Helvetica); const page = pdfDoc.getPages()[0]; const color = rgb(0,0,0); const escribir = (texto, x, y, size=8.5, width=220) => { if (!texto) return; page.drawText(String(texto).replace(/\s+/g,' ').trim(), { x, y, size, maxWidth: width, font, color }); }; const nombre = `${form.apellidoPaterno} ${form.apellidoMaterno} ${form.nombres}`.trim(); const {dd, mm, aaaa} = dividirFecha(form.fechaNacimiento); const firma = dividirFecha(form.fechaFirma); escribir(nombre, 32, 644, 8.7, 545); escribir(dd, 329, 590); escribir(mm, 360, 590); escribir(aaaa, 389, 590); escribir(form.lugarNacimiento, 429, 590, 8.5, 115); escribir(`${form.calle} ${form.numeroCasa}`, 32, 548, 8.5, 430); escribir(form.colonia, 32, 510, 8.5, 245); escribir(form.telefono, 327, 510); escribir(form.telefonoCelular, 462, 510); escribir(form.municipio, 32, 468); escribir(form.estado, 134, 468); escribir(form.pais, 230, 468); escribir(form.correo, 327, 468, 8.2, 245); escribir(form.beneficiarioRelacion, 417, 395); escribir(form.beneficiarioNombres, 32, 362, 8.7, 545); escribir(form.beneficiarioDomicilio, 32, 331, 8.2, 400); escribir(form.beneficiarioTelefono, 450, 331); escribir(form.patrocinadorNombres, 33, 242, 8.7, 360); escribir(form.numeroPatrocinador, 410, 242); escribir(form.lugarFirma, 332, 70); escribir([firma.dd, firma.mm, firma.aaaa].filter(Boolean).join('/'), 516, 70); const out = await pdfDoc.save(); const blob = new Blob([out], { type:'application/pdf' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href=url; a.download='Solicitud-de-Membresia-Rellena.pdf'; a.click(); URL.revokeObjectURL(url); } catch(e) { console.error(e); alert('No se pudo generar el PDF. Verifica que el archivo esté en public/archivos/SOLICITUD-DE-MEMBRESIA-v2.pdf'); } };
  const fields = [['apellidoPaterno','Apellido paterno'],['apellidoMaterno','Apellido materno'],['nombres','Nombres'],['fechaNacimiento','Fecha nacimiento','date'],['lugarNacimiento','Lugar nacimiento'],['calle','Calle'],['numeroCasa','Número'],['colonia','Colonia'],['municipio','Municipio'],['estado','Estado'],['pais','País'],['telefono','Teléfono'],['telefonoCelular','Celular'],['correo','Correo'],['beneficiarioNombres','Beneficiario / codistribuidor'],['beneficiarioRelacion','Relación'],['beneficiarioDomicilio','Domicilio beneficiario'],['beneficiarioTelefono','Teléfono beneficiario'],['patrocinadorNombres','Patrocinador'],['numeroPatrocinador','Número patrocinador'],['lugarFirma','Lugar firma'],['fechaFirma','Fecha firma','date']];
  return <Card className="membership"><div className="order-head"><div><h2>Solicitud de Membresía</h2><p className="hint">Formulario auxiliar para generar PDF relleno encima del formato oficial.</p></div>{onClose && <Button variant="ghost" onClick={onClose}>Cerrar</Button>}</div><div className="form-grid">{fields.map(([name,label,type='text'])=><Field key={name} label={label}><input className="input" type={type} name={name} value={form[name]} onChange={change}/></Field>)}</div><div className="doc-actions"><Button onClick={generarPDF}>Generar PDF relleno</Button><Button variant="ghost" onClick={()=>setForm(initial)}>Limpiar</Button></div></Card>;
}
